import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <nav className="px-10 pt-5">
          <Link href="/" className="text-2xl font-semibold">
            Movie <span className="text-teal-400">DB</span>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
